### ISSUE TITLE
Enable debugging for azure-openapi-validator plugin

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-openapi-validator#110]
Due to latest changes in autorest, debugging does not work for this plugin. 
We need to bring in code similar to the generators to debug the dotnet portion of the plugin.
We need to figure out how we can enable typescript debugging. 
@dsgouda if you can provide context on the dotnet work needed, it'd be great. 
@olydis any thoughts on enabling debugging on the typescript side of things?

**Comment by olydis** [comment]
# dotnet
call [that](https://github.com/Azure/autorest.common/blob/master/src/Utilities/Debugger.cs) if you see flag `debugger` active, then it'll work 100% analogous to the generators
# typescript
simply start the extension process with `--inspect-brk` (i.e. add to `start` script of extension's `package.json`), then one can use VSCode or Chrome to debug 🙂 we could tie that CLI arg to `--debugger` as well, but so far doing that (~1h work) outweighed the 5s it takes to paste that arg into the `package.json` when needed. You can actually leave `--inspect-brk` in there on your machines (running in debug mode doesn't hurt), I just wouldn't publish it like that since it prints something like `Debugger listening on ws://127.0.0.1:9229/cde7d906-82b3-4fea-b8f1-527f34c0709d` (<= navigate to that in chrome start the fun) to stderr

**Comment by dsgouda** [comment]
@veronicagg  Let me know if you still need any help here
