### ISSUE TITLE
Incorrect validation error XmsExamplesRequired 

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-openapi-validator#123]
Moving from [here](https://github.com/Azure/autorest/issues/2717)

**Comment by veronicagg** [comment]
@DheerendraRathor  are you seeing the issue when running the validation on the spec at f:\Git\azure-rest-api-specs\specification\recoveryservicesbackup\resource-manager\Microsoft.RecoveryServices\2016-12-01\backupManagement.json ?
There are no x-ms-examples in the spec as far as I can see, therefore instead of reporting one error for each operation, we're providing 1 error at the paths level to indicate there are no x-ms-examples defined.
Please let me know if this is not what you're seeing.
FYI - @olydis @dsgouda

**Comment by olydis** [comment]
@veronicagg oh we have a roll-up error in that case? Good to know 🙂 Does that make sense, though? In the reports we generate, service teams will be "punished" for providing some examples, in case they had none before.

**Comment by DheerendraRathor** [comment]
@veronicagg Thanks for clarification. Looks like that is the case.
Although I'm running validation on readme.md in directory "\azure-rest-api-specs\specification\recoveryservicesbackup\resource-manager\". 
It is reporting individual XmsExamplesRequired for version 2017-07-01 file and single one for 2016-12-01 file.

**Comment by veronicagg** [comment]
@olydis yes on the error reporting, we talked about it at the time, though flooding with errors was no good either, so we made that decision, unless we hear feedback that it's a problem we'll have it as is. In practice, when specs get examples added, they are generally all or none. @salameer is aware of this.

**Comment by veronicagg** [comment]
@DheerendraRathor it doesn't seem like I see the same when I run with the readme on my machine, feel free to send me your results if this matters to you. In any case, the rule reports individual results when you have less than 10 (arbitrary) examples missing, so you're able to tell which ones, if not we go a roll-up error, to avoid flooding/noise. As I was mentioning to @olydis in general specs have all examples or none. Let us know if you see benefits on reporting this differently for you.
Please close the issue if you're ok with this. If you'd like us to address something else, please update the issue title and ask, or open a new one. Thanks!

**Comment by DheerendraRathor** [comment]
@dsgouda Please close the issue. Looks like I can't close it.
